.\"     Title: server.properties
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/01/2021
.\"    Manual: 
.\"    Source: 
.\"
.TH "SERVER\.PROPERTIES" "4" "01/01/2021" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
server.properties - This file contains the server properties.
.SH "SYNOPSIS"
.HP 18
\fBserver\.properties\fR
.SH "DESCRIPTION"
.PP
The
server\.properties
file contains server properties which can be modified by user when needed
.PP
Editing this file requires an administrative user\.
.SH "AUTHOR"
.PP

server\.properties
was developed by opensource community\.
.SH "FILES"
.PP
Server property files\.
.SH "SEE ALSO"
.PP

\fB server.ports \fR(4)
.PP

\fIReturn to Reference Index\fR\&[2]
.SH "NOTES"
.IP " 1." 4
server.ports
.RS 4
\%server.ports.4.html
.RE
.IP " 2." 4
Return to Reference Index
.RS 4
\%refindex.html
.RE
